apiVersion: apps/v1
kind: Deployment
metadata:
  name: techbase-deployment
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: techbase-deployment
  template:
    metadata:
      labels:
        app: techbase-deployment
    spec:
      containers:
      - name: nextjs
        image: mohamedhafid825/techbase:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: techbase-secrets
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"